import { test, expect, type Page } from '@playwright/test';
import { mkdir } from 'node:fs/promises';

test('formulário de login valida dados e funciona em 320px e desktop', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByRole('textbox', { name: 'E-mail', exact: true })).toHaveValue('');
  await expect(page.getByLabel('Senha', { exact: true })).toHaveValue('');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByRole('alert')).toHaveText('Preencha seu e-mail e sua senha.');
  await page.getByRole('textbox', { name: 'E-mail', exact: true }).fill('ana@trocaja.com');
  await page.getByLabel('Senha', { exact: true }).fill('incorreta');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('E-mail ou senha incorretos');
  await page.reload();
  await page.setViewportSize({ width: 320, height: 740 });
  await page.getByText('Contas para demonstração').scrollIntoViewIfNeeded();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await mkdir('docs/evidencias', { recursive: true });
  await page.screenshot({ path: 'docs/evidencias/08-login-320.png' });
  await page.setViewportSize({ width: 1366, height: 900 });
  await page.getByRole('heading', { name: 'Bom ter você aqui.' }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'docs/evidencias/09-login-desktop.png' });
  await page.getByRole('textbox', { name: 'E-mail', exact: true }).fill('claudio@trocaja.com');
  await page.getByLabel('Senha', { exact: true }).fill('Claudio12345');
  await page.getByRole('button', { name: 'Mostrar senha' }).click();
  await expect(page.getByLabel('Senha', { exact: true })).toHaveJSProperty('type', 'text');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Olá, Cláudio' })).toBeVisible();
});

async function login(page: Page, name = 'Ana') {
  await page.getByRole('textbox', { name: 'E-mail', exact: true }).fill(`${name.toLowerCase()}@trocaja.com`);
  await page.getByLabel('Senha', { exact: true }).fill(`${name}12345`);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
}

test('fluxo completo entre dois participantes, com evidências do CP5', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await mkdir('docs/evidencias', { recursive: true });
  const capture = (name: string) => page.screenshot({ path: `docs/evidencias/${name}.png`, animations: 'disabled' });
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Entrar', exact: true })).toBeVisible();
  await capture('01-contas');
  await login(page);
  await expect(page.getByRole('heading', { name: 'Olá, Ana' })).toBeVisible();
  await page.getByRole('button', { name: 'Lançados hoje', exact: true }).click();
  await expect(page.getByText('2 produtos disponíveis')).toBeVisible();
  await page.getByRole('button', { name: 'Todos', exact: true }).click();
  await page.getByRole('button', { name: 'Jogos', exact: true }).click();
  await page.getByRole('textbox', { name: 'Buscar produtos' }).fill('PS5');
  await expect(page.getByText('1 produto disponível')).toBeVisible();
  await capture('02-home');
  await page.getByRole('button', { name: 'Ver PS5', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Selecione produtos para oferecer' })).toBeDisabled();
  await page.getByRole('checkbox', { name: 'Nintendo Switch' }).click();
  await capture('03-proposta');
  await page.getByRole('button', { name: 'Propor negociação (1)' }).click();
  await expect(page.getByText('Proposta enviada! Acompanhe o status na aba Trocas.')).toBeVisible();
  await page.getByRole('button', { name: 'Ver PS5', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Nintendo Switch' }).click();
  await page.getByRole('button', { name: 'Propor negociação (1)' }).click();
  await expect(page.getByText('Você já enviou esta proposta. Acompanhe na aba Trocas.')).toBeVisible();
  await page.getByRole('button', { name: 'Fechar proposta' }).click();
  await page.getByRole('tab', { name: 'Trocas', exact: true }).click();
  await expect(page.getByText('Aguardando resposta')).toBeVisible();
  await capture('04-trocas');
  await page.getByRole('tab', { name: 'Perfil', exact: true }).click();
  await page.getByRole('button', { name: 'Sair', exact: true }).click();
  await login(page, 'Bruno');
  await page.getByRole('tab', { name: 'Trocas', exact: true }).click();
  await page.getByRole('button', { name: 'Aceitar proposta', exact: true }).click();
  await expect(page.getByText('Proposta aceita. A conversa já está disponível na aba Negociações.')).toBeVisible();
  await page.getByRole('tab', { name: 'Negociações', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Conversas', exact: true })).toBeVisible();
  await capture('05-conversas');
  await page.getByRole('button', { name: 'Conversar com Ana Costa sobre Nintendo Switch', exact: true }).click();
  await page.getByRole('textbox', { name: 'Mensagem', exact: true }).fill('Vamos trocar na faculdade?');
  await page.getByRole('button', { name: 'Enviar mensagem' }).click();
  await expect(page.getByText('Vamos trocar na faculdade?', { exact: true }).last()).toBeVisible();
  await capture('06-chat');
  await page.goBack();
  await page.getByRole('tab', { name: 'Perfil', exact: true }).click();
  await page.getByRole('button', { name: 'Sair', exact: true }).click();
  await login(page);
  await page.getByRole('tab', { name: 'Negociações', exact: true }).click();
  await page.getByRole('button', { name: 'Conversar com Bruno Lima sobre PS5', exact: true }).click();
  await expect(page.getByText('Vamos trocar na faculdade?', { exact: true }).last()).toBeVisible();
  await page.goBack();
  await page.getByRole('tab', { name: 'Perfil', exact: true }).click();
  await expect(page.getByText('Catálogo local de demonstração. Supabase não configurado.')).toBeVisible();
  await capture('07-perfil');
  await page.reload();
  await expect(page.getByRole('button', { name: 'Entrar', exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});

test('busca vazia, cancelamento e recusa mantêm o histórico consistente', async ({ page }) => {
  await page.goto('/');
  await login(page);
  await page.getByRole('textbox', { name: 'Buscar produtos' }).fill('inexistente');
  await expect(page.getByText('Nenhum produto encontrado. Altere a busca ou limpe os filtros.')).toBeVisible();
  await page.getByRole('textbox', { name: 'Buscar produtos' }).fill('PS5');
  await page.getByRole('button', { name: 'Ver PS5', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Nintendo Switch' }).click();
  await page.getByRole('button', { name: 'Fechar proposta' }).click();
  await page.getByRole('button', { name: 'Ver PS5', exact: true }).click();
  await expect(page.getByRole('checkbox', { name: 'Nintendo Switch' })).not.toBeChecked();
  await page.getByRole('checkbox', { name: 'Nintendo Switch' }).click();
  await page.getByRole('button', { name: 'Propor negociação (1)' }).click();
  await page.getByRole('tab', { name: 'Trocas', exact: true }).click();
  await page.getByRole('button', { name: 'Cancelar proposta', exact: true }).click();
  await expect(page.getByText('Cancelada', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Recusar', exact: true }).click();
  await expect(page.getByText('Recusada', { exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Negociações', exact: true }).click();
  await expect(page.getByRole('button', { name: /^Conversar com Bruno Lima sobre/ })).toHaveCount(1);
  await expect(page.getByRole('button', { name: /^Conversar com Carla Souza sobre/ })).toHaveCount(1);
});
